version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  azure-language:
    image: mcr.microsoft.com/azure-cognitive-services/textanalytics/language:latest
    container_name: azure-language
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "5000:5000"
    environment:
      - Eula=accept
      - Billing=${AZURE_LANGUAGE_BILLING_URL}
      - ApiKey=${AZURE_LANGUAGE_API_KEY}
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: "2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 30s
      timeout: 5s
      retries: 5

  # azure-ner:
  #   image: mcr.microsoft.com/azure-cognitive-services/textanalytics/ner:latest
  #   container_name: azure-ner
  #   restart: unless-stopped
  #   platform: linux/amd64
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     - Eula=accept
  #     - Billing=${AZURE_NER_BILLING_URL}
  #     - ApiKey=${AZURE_NER_API_KEY}
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 6g
  #         cpus: "2"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5001/status"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 5

volumes:
  qdrant_data:
